# Generated by Django 5.2.4 on 2025-07-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='survey_answered',
            field=models.BooleanField(default=False),
        ),
    ]
