# Generated by Django 5.2.4 on 2025-07-17 12:24

import ecotrack.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0002_user_survey_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='habits',
            field=models.JSONField(blank=True, default=ecotrack.models.get_default_dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_data',
            field=models.JSONField(blank=True, default=ecotrack.models.get_default_dict),
        ),
    ]
