# Generated by Django 5.2.4 on 2025-07-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0004_user_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='habits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
