# Generated by Django 5.2.4 on 2025-07-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0005_alter_user_habits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='habit_checked_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
