# Generated by Django 5.2.4 on 2025-07-19 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0006_user_habit_checked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='habit_checked_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 7, 18, 17, 0, 5, 837164), null=True),
        ),
    ]
