# Generated by Django 5.2.4 on 2025-07-19 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0007_alter_user_habit_checked_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='habit_checked_date',
        ),
        migrations.AddField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 7, 18, 19, 52, 18, 633382), null=True),
        ),
    ]
