# Generated by Django 5.2.4 on 2025-07-22 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0009_remove_user_age_user_days_since_last_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='habits_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 7, 21, 22, 18, 57, 184762), null=True),
        ),
    ]
