# Generated by Django 5.2.4 on 2025-07-22 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0010_user_habits_today_alter_user_last_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 7, 21, 22, 21, 43, 896920), null=True),
        ),
    ]
