# Generated by Django 5.2.4 on 2025-07-23 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0011_alter_user_last_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_4_footprint_measurements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 7, 22, 16, 2, 32, 362970), null=True),
        ),
    ]
