# Generated by Django 5.2.6 on 2025-09-17 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0014_alter_user_last_checkin_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 16, 17, 35, 14, 341707), null=True),
        ),
    ]
