# Generated by Django 5.2.6 on 2025-09-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0014_pushsubscription_last_sent_fields'),
        ('ecotrack', '0015_alter_user_last_checkin'),
    ]

    operations = [
    ]
