# Generated by Django 5.2.6 on 2025-09-17 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0016_merge_20250917_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 16, 20, 45, 41, 317383), null=True),
        ),
    ]
