# Generated by Django 5.2.6 on 2025-09-18 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0018_alter_user_last_checkin_community_communitymessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 17, 18, 1, 43, 629624), null=True),
        ),
    ]
