# Generated by Django 5.2.6 on 2025-09-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0021_alter_user_last_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='device_type',
            field=models.CharField(blank=True, default='web', max_length=50, null=True),
        ),
    ]