# Generated by Django 5.2.6 on 2025-09-19 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0022_add_fcm_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 18, 22, 27, 31, 343306), null=True),
        ),
    ]
