# Generated by Django 5.2.6 on 2025-09-20 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0023_alter_user_last_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 19, 16, 41, 15, 995185), null=True),
        ),
    ]
