# Generated by Django 5.2.6 on 2025-09-24 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0026_pushsubscription_onesignal'),
    ]

    operations = [
        # No operations needed - fields already exist in database
    ]
