# Generated by Django 5.2.6 on 2025-09-22 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0026_pushsubscription_onesignal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 21, 16, 23, 8, 883967), null=True),
        ),
    ]
