# Generated by Django 5.2.6 on 2025-09-24 11:15

import ecotrack.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0028_alter_user_last_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=ecotrack.models.default_last_checkin, null=True),
        ),
    ]
