# Generated by Django 5.2.6 on 2025-09-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0026_pushsubscription_onesignal'),
        ('ecotrack', '0029_alter_user_last_checkin'),
    ]

    operations = [
    ]
