# Generated by Django 5.2.6 on 2025-09-24 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0030_merge_20250924_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='provider',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='push_provider',
            field=models.CharField(db_column='provider', default='fcm', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 23, 17, 36, 52, 697509), null=True),
        ),
    ]
